// Builds the throwaway project a benchmark runs in: the two Taskly builds, the persona and one
// generated study per brain and arm. The builds are served from `build-a` and `build-b`, and study
// ids use the same letters, so no file or id the participant's desktop or the analyst receives says
// which arm it is. The manifest beside the project keeps the mapping.

import { createHash } from "node:crypto";
import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { Arm } from "../taskly/answer-key.js";
import type { Mission } from "../taskly/missions.js";
import type { Brain } from "./plan.js";

export const REPO_ROOT = path.resolve(import.meta.dirname, "..", "..");
const PERSONA_ID = "synthetic-new-user";
const BUILD_DIR: Record<Arm, string> = { planted: "build-a", clean: "build-b" };
/** The participant's session limit, matching humanish/studies/detect-taskly-*.yaml. */
export const SESSION_TIMEOUT_MS = 600_000;

export function sha256(bytes: string | Buffer): string {
  return createHash("sha256").update(bytes).digest("hex");
}

export interface FixtureDigests {
  plantedAppJs: string;
  cleanAppJs: string;
  indexHtml: string;
  persona: string;
}

export function fixtureDigests(): FixtureDigests {
  const read = (relative: string): Buffer => readFileSync(path.join(REPO_ROOT, relative));
  return {
    plantedAppJs: sha256(read("bench/taskly-planted/app.js")),
    cleanAppJs: sha256(read("bench/taskly-clean/app.js")),
    indexHtml: sha256(read("bench/taskly-planted/index.html")),
    persona: sha256(read(`humanish/personas/${PERSONA_ID}.yaml`)),
  };
}

export function studyId(brain: Brain, arm: Arm): string {
  return `bench-taskly-${BUILD_DIR[arm].slice(-1)}-${brain.id}`;
}

/** The study manifest for one brain and arm. JSON-quoted scalars are valid YAML. */
export function studyYaml(
  brain: Brain,
  arm: Arm,
  mission: Mission,
  participantCapUsd: number,
): string {
  const id = studyId(brain, arm);
  const actor = Object.entries(brain.actor)
    .map(([key, value]) => `  ${key}: ${JSON.stringify(value)}`)
    .join("\n");
  const caps = brain.priced ? `caps:\n  maxUsd: ${participantCapUsd}\n` : "";
  return `schema: humanish.study.v3
id: ${id}
title: ${JSON.stringify(`Taskly benchmark, build ${BUILD_DIR[arm].slice(-1)}, ${brain.id}`)}
description: "Generated by bench/run.ts for one benchmark invocation."
route: computer-use
mode: live
subject:
  source: local-tree
  serve:
    start: python3 -m http.server 8000 --directory ${BUILD_DIR[arm]}
    url: http://127.0.0.1:8000/
actor:
${actor}
  persona: ${PERSONA_ID}
  mission: ${JSON.stringify(mission.text)}
${caps}execution:
  target: e2b-desktop
  timeoutMs: ${SESSION_TIMEOUT_MS}
review:
  analysis: false
policies:
  allowPrivateRepoAccess: false
  allowProviderCredentials: false
  allowPaymentCredentials: false
  allowGitHubMutation: false
`;
}

/** Write the project: both builds, the persona and a study per brain and arm. */
export function writeProject(
  projectDir: string,
  brains: readonly Brain[],
  mission: Mission,
  participantCapUsd: number,
): void {
  mkdirSync(path.join(projectDir, "humanish", "studies"), { recursive: true });
  mkdirSync(path.join(projectDir, "humanish", "personas"), { recursive: true });
  cpSync(path.join(REPO_ROOT, "bench", "taskly-planted"), path.join(projectDir, BUILD_DIR.planted), {
    recursive: true,
  });
  cpSync(path.join(REPO_ROOT, "bench", "taskly-clean"), path.join(projectDir, BUILD_DIR.clean), {
    recursive: true,
  });
  cpSync(
    path.join(REPO_ROOT, "humanish", "personas", `${PERSONA_ID}.yaml`),
    path.join(projectDir, "humanish", "personas", `${PERSONA_ID}.yaml`),
  );
  for (const brain of brains) {
    for (const arm of ["planted", "clean"] as const) {
      writeFileSync(
        path.join(projectDir, "humanish", "studies", `${studyId(brain, arm)}.yaml`),
        studyYaml(brain, arm, mission, participantCapUsd),
      );
    }
  }
}
