/** Read Commander metadata only; constructing the program does not run commands or discover keys. */
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Command } from "commander";
import { createProgram } from "../src/program.js";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const referencePath = resolve(root, "site/content/docs/cli.mdx");
const llmsPath = resolve(root, "site/public/llms.txt");
const start = "<!-- humanish-cli:start -->";
const end = "<!-- humanish-cli:end -->";
const check = process.argv.includes("--check");
const program = createProgram();

function walk(command: Command, trail: string[] = []): { command: Command; name: string; depth: number }[] {
  return command.commands.flatMap((child) => {
    const names = [...trail, child.name()];
    return [{ command: child, name: `humanish ${names.join(" ")}`, depth: names.length }, ...walk(child, names)];
  });
}

const entries = walk(program);
const mdxText = (text: string) => text.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll("{", "&#123;").replaceAll("}", "&#125;");
const tableText = (text: string) => mdxText(text).replaceAll("|", "\\|").replaceAll("\n", " ");

function commandReference(command: Command): string[] {
  const help = command.createHelp();
  const args = help.visibleArguments(command);
  const options = help.visibleOptions(command);
  return [
    "```text",
    help.commandUsage(command),
    "```",
    ...(args.length ? [
      "",
      "| Argument | Description |",
      "| --- | --- |",
      ...args.map((arg) => `| \`${help.argumentTerm(arg)}\` | ${tableText(help.argumentDescription(arg))} |`)
    ] : []),
    ...(options.length ? [
      "",
      "| Option | Description |",
      "| --- | --- |",
      ...options.map((option) => `| \`${help.optionTerm(option).replaceAll("|", "\\|")}\` | ${tableText(help.optionDescription(option))} |`)
    ] : [])
  ];
}

const reference = [
  "---",
  "title: CLI reference",
  "description: Every command, argument, and option in the Humanish CLI.",
  "---",
  "",
  `{/* Generated by scripts/generate-cli-docs.ts from createProgram(). Do not edit by hand. */}`,
  "",
  `Reference for **Humanish ${program.version()}**. Run \`npx humanish --version\` to check your installation, or \`npx humanish <command> --help\` for its exact flags.`,
  "",
  "Start with the [quickstart](/docs). The examples below use the installed `humanish` binary; prefix them with `npx` from your project if it is not on your PATH.",
  "",
  "`--json` returns machine-readable responses where supported. `tui` is an interactive surface for a human and refuses a non-TTY; coding agents should use the command outputs.",
  "",
  "## humanish",
  "",
  ...commandReference(program),
  "",
  ...entries.filter(({ depth }) => depth === 1).map(({ name, command }) => `- [${name}](#${name.replaceAll(" ", "-")}): ${mdxText(command.summary() || command.description())}`),
  ...entries.flatMap(({ command, name, depth }) => [
    "",
    `${depth === 1 ? "##" : "###"} ${name}`,
    "",
    mdxText(command.description()),
    "",
    ...commandReference(command)
  ]),
  ""
].join("\n");

const commandIndex = [
  start,
  "",
  "This command index is generated from the shipped CLI. Full arguments and options: https://humanish.dev/docs/cli",
  "",
  ...entries.map(({ command, name }) => `- \`${name}\`: ${command.summary() || command.description()}`),
  "",
  end
].join("\n");
const llms = await readFile(llmsPath, "utf8");
if (!llms.includes(start) || !llms.includes(end)) throw new Error("Missing CLI section markers in llms.txt");
const nextLlms = llms.slice(0, llms.indexOf(start)) + commandIndex + llms.slice(llms.indexOf(end) + end.length);

let stale = false;
for (const [path, expected] of [[referencePath, reference], [llmsPath, nextLlms]]) {
  const actual = await readFile(path, "utf8").catch(() => "");
  if (actual === expected) continue;
  if (check) {
    console.error(`${path.slice(root.length + 1)} is stale; run pnpm docs:generate`);
    stale = true;
  } else {
    await writeFile(path, expected);
    console.log(`Generated ${path.slice(root.length + 1)}`);
  }
}
if (stale) process.exitCode = 1;
else console.log(`CLI docs ${check ? "match" : "generated from"} ${entries.length} commands and subcommands.`);
